title: Las Vegas Real Estate Video Blog with Katie Meadows
description: Our mission at The Richardson Group is to be your best resource for Las Vegas real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The The Richardson Group, your professional Las Vegas Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Katie Meadows
  title:
  license_number:
  about_markdown: |
    I had a dream of helping people and I thought what better way than to help families and friends find them somewhere they can build and make memories.  My job is not only to find a home for clients but to help guide them through the process along the way and help them reach all their goals.
  brand: The Richardson Group
  brokerage: REAL Broker LLC
  market: Las Vegas
  address: '7448 Sahara Avenue #103 Las Vegas, NV 89117'
  phone: 702-769-4866
  phone_type:
  phone2:
  phone2_type:
  email:
  url: https://therichardsongroup.vegas

forms:
  sitekey:

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://therichardsongroup.vegas/sell-a-home/291/The-Richardson-Group-at-REAL-Broker-LLC
  second_CTA_text: Home Search
  second_CTA_URL: https://therichardsongroup.vegas/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Las Vegas Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://therichardsongroup.vegas/sell-a-home/291/The-Richardson-Group-at-REAL-Broker-LLC

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Las Vegas Home?"
    CTA_text2: "Search the entire MLS for your Las Vegas home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://therichardsongroup.vegas/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url:
  youtube_url:
  twitter_url:
  instagram_url: https://instagram.com/johnnyrichardsonjr
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:
  google_business_url:

podcast:
  title: 'Las Vegas Real Estate Podcast with Katie Meadows'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Las Vegas Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from The Richardson Group - your professional Las Vegas Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Las Vegas, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Katie Meadows'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Las Vegas Real Estate Video Blog
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg
  header_overlay: rgba(0, 0, 0, 0.3)

site_colors:
  brand_color: '#05C3F9'
  theme_color: '#000000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
