audit_header: false
title: Golden Corner of South Carolina Real Estate Video Blog with Les Walden
description: Our mission at Les Walden Real Estate Team is to be your best resource for Golden Corner of South Carolina real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Les Walden Real Estate Team, your professional Golden Corner of South Carolina Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Les Walden
  title:
  license_number:
  about_markdown: |
    Born and raised in South Carolina Les loves to call the Golden Corner Home. Hearing him talk about why he makes this area home leaves no doubt that he is a walking-talking commercial for the area. "I just love everything we have to offer. From the lakes to the mountains, all the local shops and incredible food, comfortable weather all four seasons, and Clemson University in our back door we have something for everyone." says Les.

    Les lives on Lake Keowee and has two daughters. His oldest is a graduate of Clemson University (following in dad's footsteps) and a Special Education Teacher. His younger daughter attends Seneca High School. If he is not helping someone accomplish their real estate dreams, he can be found floating around the lake or taking in an event at Clemson University (Go Tigers!).
  brand: Les Walden Real Estate Team
  brokerage:
  market: Golden Corner of South Carolina
  address: 10700 Clemson Blvd Seneca SC 29678
  phone: 864-985-1234
  phone_type:
  phone2:
  phone2_type:
  email:
  url: http://leswaldenrealestate.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: /homevalue/
  second_CTA_text: Home Search
  second_CTA_URL: /homesearch/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Golden Corner of South Carolina Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: /homevalue/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Golden Corner of South Carolina Home?"
    CTA_text2: "Search the entire MLS for your Golden Corner of South Carolina home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: /homesearch/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/LesWaldenTeam
  linkedin_url: https://www.linkedin.com/in/leswaldenrealestate
  youtube_url: https://www.youtube.com/channel/UCVtYlWmSzAIjlQx8GhTsTuA
  twitter_url: https://twitter.com/leswalden
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Golden Corner of South Carolina Real Estate Podcast with Les Walden'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Golden Corner of South Carolina Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Les Walden Real Estate Team - your professional Golden Corner of South Carolina Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Golden Corner of South Carolina, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Les Walden'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text: Golden Corner of South Carolina Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#5587b9'
  theme_color: '#999999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
